[package]
name = "ledd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm   = "0.26"
# ratatui = "0.22.0"
# reedline = "0.25.0"
# rustyline = "12.0.0"
